spring.application.name=anime_tier


# DB ?? ??
spring.datasource.url=jdbc:postgresql://ani-vector.cgxqyuymuxiw.us-east-1.rds.amazonaws.com:5432/postgres
spring.datasource.username=kim_admin
spring.datasource.password=2ternityA!
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate ??
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# local transformer engine
spring.ai.model.embedding=transformers

# korean <-> english
spring.ai.embedding.transformer.model-uri=https://huggingface.co/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/resolve/main/model.onnx



spring.ai.aws.bedrock.region=us-east-1


spring.ai.aws.bedrock.credentials.access-key=${AWS_ACCESS_KEY_ID}
spring.ai.aws.bedrock.credentials.secret-key=${AWS_SECRET_ACCESS_KEY}

spring.ai.aws.bedrock.chat.enabled=true
spring.ai.aws.bedrock.chat.options.model=amazon.nova-micro-v1:0


# turn off bedrock embed
spring.ai.aws.bedrock.titan.embedding.enabled=false
spring.ai.aws.bedrock.cohere.embedding.enabled=false